{
 "title": "Linux SNMP Observability",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "System Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"MemoryAvail\"})",
     "query": "test.test_0031.find({\"metadata.label\":\"MemoryAvail\"})"
    },
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"systemSwapIn\"})",
     "query": "test.test_0031.find({\"metadata.label\":\"systemSwapIn\"})"
    },
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"systemSwapOut\"})",
     "query": "test.test_0031.find({\"metadata.label\":\"systemSwapOut\"})"
    }
   ]
  },
  {
   "title": "System CPU Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"CPU IDLE\"})",
     "query": "test.test_0031.find({\"metadata.label\": \"CPU IDLE\"})"
    },
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"ProcessorLoad\"})",
     "query": "test.test_0031.find({\"metadata.label\":\"ProcessorLoad\"})"
    }
   ]
  },
  {
   "title": "Disk IO Written",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"diskIoWritten\"})",
     "query": "test.test_0031.find({\"metadata.label\": \"diskIoWritten\"})"
    }
   ]
  },
  {
   "title": "Disk IO Read",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"diskIoRead\"})",
     "query": "test.test_0031.find({\"metadata.label\": \"diskIoRead\"})"
    }
   ]
  },
  {
   "title": "Network Interface Packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "parsedQuery": "test.test_0031.find({\"metadata.label\":\"NIC\"})",
     "query": "test.test_0031.find({\"metadata.label\":\"NIC\"})"
    }
   ]
  }
 ]
}